# Generated by Django 2.1.7 on 2019-04-15 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190415_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='end_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='turma',
            name='start_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
