# Generated by Django 2.1.7 on 2019-04-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190415_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviso',
            old_name='turma',
            new_name='turma_id',
        ),
        migrations.RenameField(
            model_name='aviso',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='ciclo',
            new_name='ciclo_id',
        ),
    ]
