# Generated by Django 2.1.7 on 2019-04-16 00:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190415_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=datetime.datetime.today)),
                ('end_date', models.DateTimeField(default=datetime.datetime.today)),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
                ('total_classes', models.IntegerField()),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Turma')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Turma')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('turma_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Turma')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presences', models.IntegerField()),
                ('is_replacement', models.BooleanField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
                ('aula_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Aula')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
        ),
    ]
