# Generated by Django 2.1.7 on 2019-04-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_aluno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aviso',
            old_name='turma_id',
            new_name='turma',
        ),
        migrations.RenameField(
            model_name='aviso',
            old_name='user_id',
            new_name='user',
        ),
    ]
