# Generated by Django 2.1.7 on 2019-05-07 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190507_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presenca',
            old_name='aula_id',
            new_name='aula',
        ),
        migrations.RenameField(
            model_name='presenca',
            old_name='user_id',
            new_name='user',
        ),
    ]
