# Generated by Django 2.1.7 on 2019-05-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20190507_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='user',
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='end_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='presences',
        ),
        migrations.AddField(
            model_name='presenca',
            name='presence',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
