# Generated by Django 2.1.7 on 2019-05-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20190512_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='total_classes',
        ),
        migrations.AddField(
            model_name='turma',
            name='actual_class',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
