# Generated by Django 2.1.7 on 2019-05-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20190513_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='absences',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
