# Generated by Django 2.1.7 on 2019-05-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_presenca_absences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='absences',
        ),
        migrations.AddField(
            model_name='matricula',
            name='absences',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
