# Generated by Django 2.1.7 on 2019-05-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20190513_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='name',
            field=models.CharField(default='Aula', max_length=50),
            preserve_default=False,
        ),
    ]
