# Generated by Django 2.1.7 on 2019-05-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_aula_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='actual_class',
            field=models.IntegerField(default=0),
        ),
    ]
