# Generated by Django 2.1.7 on 2019-05-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20190516_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenca',
            name='presence',
        ),
        migrations.AddField(
            model_name='presenca',
            name='presences',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
