# Generated by Django 2.1.7 on 2019-05-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_turma_first_attendance'),
        ('myapp', '0018_auto_20190523_2233'),
    ]

    operations = [
    ]
