# Generated by Django 2.1.7 on 2019-05-27 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_merge_20190527_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Turma'),
            preserve_default=False,
        ),
    ]
