# Generated by Django 2.1.7 on 2019-05-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_presenca_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenca',
            name='original_turma',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
