# Generated by Django 2.1.7 on 2019-06-02 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_presenca_original_turma'),
        ('myapp', '0020_merge_20190527_2247'),
    ]

    operations = [
    ]
