# Generated by Django 2.1.7 on 2019-06-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_merge_20190602_1257'),
        ('myapp', '0020_merge_20190527_2334'),
    ]

    operations = [
    ]
