# Generated by Django 2.1.7 on 2019-06-03 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_matricula_graduated'),
        ('myapp', '0024_merge_20190602_1331'),
    ]

    operations = [
    ]
