# Generated by Django 2.1.7 on 2019-06-08 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_merge_20190602_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='date',
        ),
    ]
