# Generated by Django 2.1.7 on 2019-06-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_merge_20190603_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='new_ciclo',
            field=models.CharField(default='needApprove', max_length=50),
        ),
    ]
