# Generated by Django 2.1.7 on 2019-06-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_matricula_new_ciclo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='date',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='new_ciclo',
        ),
    ]
